title: "Your Name"
description: "Personal Academic Website"
author: "Marek Słoński"
email: "marek.slonski@pk.edu.pl"
theme: jekyll-theme-minimal
# Navigation
header_pages:
  - index.md
  - research.md
  - cv.md
  - contact.md
